### ISSUE TITLE
Make links a different color than body text. Add more distinguishable mouse hover states.

### ISSUE THREAD

**Issue by joelhsmith** [a11ywatch/web#101]
I can't tell what elements on the page are clickable until I hover over it or try to click on it.

I would like links to be blue and get an underline on hover.

**Comment by joelhsmith** [comment]
I should not have been specific about it being "link text". The intent of the WCAG 1.4.1 rule is that people can tell what is clickable and what is not clickable. If the underlying HTML happens to be a button and not a link that does not matter to the user.  The overriding concept is that clickable things need to be differentiated.  

When I checked my dashboard today the areas outlined in pink (from the screenshot link) was all black, like before. Was the intent of the 3bb4924 that those clickable elements would also become blue?

**Comment by j-mendez** [comment]
Hi @joelhsmith , I am not sure what exactly you are referring too. The criteria passes the rules and the button/links are distinguishable. If you are referring to links that are black and change color on hover ex: 

![link that is black on github](https://user-images.githubusercontent.com/8095978/215521672-a8afe79a-3444-4b64-8b27-eefe829fc2d3.png).

**Comment by joelhsmith** [comment]
Sorry, I'm not doing a very good job at explaining. [This image is what I was hoping for](https://ibb.co/2vcch0B). When links, buttons, icons, and text is black; it requires a mouse hover to discover what is clickable. Touch screen users can not hover over items like mouse users can.  They would need to tap around to discover which elements go places.

They don't need to be blue, like the pic. Anything with a 3:1 contrast ratio compared to the black text would be great. 

Thanks for your consideration :-) I'll stop now.
